name: Node CI

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    branches:
      - main

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - name: npm install, lint, build, and test
        run: |
          yarn install --immutable
          yarn lint
          yarn build
          yarn test
        env:
          CI: true

  publish-npm:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --immutable
      - run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SESAMECARE_OSS_NPM_TOKEN }}
        run: |
          yarn dlx semantic-release
